### ISSUE TITLE
Manual Reviews for WooCommerce - Removed from Repository

### ISSUE THREAD

**Issue by KoolPal** [lukecav/awesome-woocommerce#2]
Hi,

You may want to remove: Manual Reviews for WooCommerce - A simple and easy way to add products reviews from your WordPress dashboard.

This has been removed from the plugin repository.

I was searching for this plugin and landed on your project!

Awesome stuff! Please keep this updated

Thanks

**Comment by lukecav** [comment]
https://github.com/lukecav/awesome-woocommerce/commit/716a48156306ed6eba5a60b77e59bedfa219b37a
