### ISSUE TITLE
Shopping cart abandonment link is dead

### ISSUE THREAD

**Issue by Marcoevich** [lukecav/awesome-woocommerce#4]
Hello, your Google Analytics shopping cart abandonment link is dead: https://blog.lemonstand.com/cart-abandonment-google-analytics/

**Comment by lukecav** [comment]
Looks like the blog closed.
https://blog.lemonstand.com/

**Comment by lukecav** [comment]
Going to replace the link with this one instead.
https://ecommercecosmos.com/tracking-cart-abandonment-in-google-analytics/

**Comment by lukecav** [comment]
https://github.com/lukecav/awesome-woocommerce/commit/2a86d288f681daf6fdf20f705b59b380bf24c862
